### PR TITLE
Precommit linting cleanup

### PR DESCRIPTION
**Pull request by Helithumper**
@jeffreydivi here's 32 changed files with 937 additions and 620 deletions. I ran all of the provided testing code over it so should be good to merge! (right?)

### CODE REVIEW

**Comment by jeffreydivi** [comment]
Black formatting is now a thing.

**Comment by Helithumper** [comment]
Ruff. Ruff. 🐶

**Comment by Helithumper** [comment]
Looks like this needs a rebase now due to other commits w.r.t. precommit.

**Comment by Helithumper** [comment]
Already completed by https://github.com/HackUCF/OnboardLite/pull/22

**Pull request closed without merging**
